Repository cmu-db/postgres, pull requests merged in 2021-11, with the labels that each got.

#12 Bring over initial TScout code.
  cmudb/tscout/README.md
  cmudb/tscout/collector.c
  cmudb/tscout/markers.c
  cmudb/tscout/probes.c
  cmudb/tscout/test2.py
  cmudb/tscout/tscout.c
  cmudb/tscout/tscout.py
Labels: feature

#13 Integrate TScout with PostgreSQL via libclang.
  cmudb/tscout/.clang-format
  cmudb/tscout/README.md
  cmudb/tscout/clang_parser.py
  cmudb/tscout/collector.c
  cmudb/tscout/markers.c
  cmudb/tscout/model.py
  cmudb/tscout/requirements.txt
  cmudb/tscout/test2.py
  cmudb/tscout/tscout.c
  cmudb/tscout/tscout.py
Labels: ready-for-review, feature

#14 Fix TScout/Collector formatting of float and double output.
  cmudb/tscout/model.py
  cmudb/tscout/tscout.py
Labels: ready-for-review, feature

#15 Refactor executors for TScout markers
  cmudb/tscout/model.py
  cmudb/tscout/tscout.c
  cmudb/tscout/tscout.py
  src/backend/executor/nodeAgg.c
  src/backend/executor/nodeAppend.c
  src/backend/executor/nodeCtescan.c
  src/backend/executor/nodeCustom.c
  src/backend/executor/nodeForeignscan.c
  src/backend/executor/nodeFunctionscan.c
  src/backend/executor/nodeGather.c
  src/backend/executor/nodeGatherMerge.c
  src/backend/executor/nodeGroup.c
  src/backend/executor/nodeHashjoin.c
  src/backend/executor/nodeIncrementalSort.c
  src/backend/executor/nodeIndexonlyscan.c
  src/backend/executor/nodeIndexscan.c
  src/backend/executor/nodeLimit.c
  src/backend/executor/nodeLockRows.c
  src/backend/executor/nodeMaterial.c
  src/backend/executor/nodeMergeAppend.c
  src/backend/executor/nodeMergejoin.c
  src/backend/executor/nodeModifyTable.c
  src/backend/executor/nodeNamedtuplestorescan.c
  src/backend/executor/nodeNestloop.c
  src/backend/executor/nodeProjectSet.c
  src/backend/executor/nodeRecursiveunion.c
  src/backend/executor/nodeResult.c
  src/backend/executor/nodeSamplescan.c
  src/backend/executor/nodeSeqscan.c
  src/backend/executor/nodeSetOp.c
  src/backend/executor/nodeSort.c
  src/backend/executor/nodeSubplan.c
  src/backend/executor/nodeSubqueryscan.c
  src/backend/executor/nodeTableFuncscan.c
  src/backend/executor/nodeTidscan.c
  src/backend/executor/nodeUnique.c
  src/backend/executor/nodeValuesscan.c
  src/backend/executor/nodeWindowAgg.c
  src/backend/executor/nodeWorktablescan.c
  src/backend/postmaster/postmaster.c
  src/include/tscout/executors.h
  src/include/tscout/marker.h
Labels: ready-for-review, low-priority

#16 Fix exception with struct.pack for float/double features
  cmudb/tscout/model.py
Labels: ready-for-review

#18 TS: A bit more error handling in marker code
  cmudb/tscout/markers.c
  cmudb/tscout/probes.c
Labels: ready-for-review, low-priority

#20 Fix for recursive OUs
  cmudb/tscout/collector.c
  cmudb/tscout/markers.c
  cmudb/tscout/tscout.py
  src/backend/executor/nodeHashjoin.c
  src/backend/executor/nodeSubplan.c
  src/include/tscout/executors.h
Labels: ready-for-review

#21 Accumulate BEGIN/END markers, flush at FEATURES
  cmudb/tscout/collector.c
  cmudb/tscout/markers.c
  cmudb/tscout/tscout.py
  src/backend/executor/nodeAgg.c
  src/backend/executor/nodeAppend.c
  src/backend/executor/nodeCtescan.c
  src/backend/executor/nodeCustom.c
  src/backend/executor/nodeForeignscan.c
  src/backend/executor/nodeFunctionscan.c
  src/backend/executor/nodeGather.c
  src/backend/executor/nodeGatherMerge.c
  src/backend/executor/nodeGroup.c
  src/backend/executor/nodeHashjoin.c
  src/backend/executor/nodeIncrementalSort.c
  src/backend/executor/nodeIndexonlyscan.c
  src/backend/executor/nodeIndexscan.c
  src/backend/executor/nodeLimit.c
  src/backend/executor/nodeLockRows.c
  src/backend/executor/nodeMaterial.c
  src/backend/executor/nodeMergeAppend.c
  src/backend/executor/nodeMergejoin.c
  src/backend/executor/nodeModifyTable.c
  src/backend/executor/nodeNamedtuplestorescan.c
  src/backend/executor/nodeNestloop.c
  src/backend/executor/nodeProjectSet.c
  src/backend/executor/nodeRecursiveunion.c
  src/backend/executor/nodeResult.c
  src/backend/executor/nodeSamplescan.c
  src/backend/executor/nodeSeqscan.c
  src/backend/executor/nodeSetOp.c
  src/backend/executor/nodeSort.c
  src/backend/executor/nodeSubplan.c
  src/backend/executor/nodeSubqueryscan.c
  src/backend/executor/nodeTableFuncscan.c
  src/backend/executor/nodeTidscan.c
  src/backend/executor/nodeUnique.c
  src/backend/executor/nodeValuesscan.c
  src/backend/executor/nodeWindowAgg.c
  src/backend/executor/nodeWorktablescan.c
  src/include/tscout/executors.h
Labels: ready-for-review

#22 Replace Plan node with more detailed version
  cmudb/tscout/model.py
Labels: blocked

#24 ClangParser refinements
  cmudb/tscout/clang_parser.py
  src/include/access/attnum.h
  src/include/nodes/execnodes.h
Labels: ready-for-review

#26 Clangparser refinements, again
  cmudb/tscout/clang_parser.py
  src/include/access/attnum.h
  src/include/nodes/execnodes.h
Labels: ready-for-review
