Repository cmu-db/postgres, pull requests merged in 2022-02, with the labels that each got.

#46 Add EXPLAIN (FORMAT tscout) (extension "Hutch") to display features for the behavior models.
  cmudb/CMakeLists.txt
  cmudb/extensions/CMakeLists.txt
  cmudb/extensions/hutch/.gitignore
  cmudb/extensions/hutch/CMakeLists.txt
  cmudb/extensions/hutch/Makefile
  cmudb/extensions/hutch/hutch_extension--0.0.1.sql
  cmudb/extensions/hutch/hutch_extension.control
  cmudb/extensions/hutch/main.c
  cmudb/extensions/hutch/operating_unit_codegen.c
  cmudb/extensions/hutch/tscout_feature_gen.py
  cmudb/tscout/clang_parser.py
  cmudb/tscout/model.py
  src/backend/commands/explain.c
  src/include/commands/explain.h
Labels: ready-for-review, feature

#53 Fix interaction between Hutch and HypoPG.
  cmudb/extensions/hutch/main.c
Labels: ready-for-review, ready-for-ci

#56 Fix `PYTHONPATH` for `hutch_install`.
  dodos/hutch.py
Labels: infrastructure, ready-for-review
